---
- name: install and test docker
  hosts: all
  become: true
  vars_files:
    - secret.yaml

  tasks:
    - name: install prequisites
      apt: 
        name:
          - python3
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: yes

    - name: add apt key for docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: add ubuntu repo to fetch docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable

    - name: install Docker
      apt: 
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Auto Restart Docker on Crash
      systemd:
        name: docker
        state: started
        enabled: true

    - name: add user
      user:
        name: dockeruser
        group: docker

    - name: provide permissions to dockeruser
      shell: 'usermod -aG docker dockeruser' 

    - name: install python package manager
      apt:
        name: python3-pip
    - name: install python sdk to manage docker
      #become_user: dockeruser
      pip:
        name:
          - docker
          - docker-compose
          - ansible_vault

    - name: Use Encrypted Password
      docker_login:
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password }}"
    
    - name: pull an image
      docker_image:
        name: zohaib96/hello-world-python:1.0
        source: pull

    - name: run the image
      docker_container:
        name: HelloWorld
        image: zohaib96/hello-world-python:1.0
        state: started
        detach:  true
        network_mode: host 
      become_user: dockeruser


